# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todos_pb2 as todos__pb2


class TodosStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateTodo = channel.unary_unary(
        '/todos.Todos/CreateTodo',
        request_serializer=todos__pb2.Todo.SerializeToString,
        response_deserializer=todos__pb2.TodoRequest.FromString,
        )
    self.DeleteTodo = channel.unary_unary(
        '/todos.Todos/DeleteTodo',
        request_serializer=todos__pb2.TodoRequest.SerializeToString,
        response_deserializer=todos__pb2.TodoStatus.FromString,
        )
    self.UpdateTodo = channel.unary_unary(
        '/todos.Todos/UpdateTodo',
        request_serializer=todos__pb2.TodoRequest.SerializeToString,
        response_deserializer=todos__pb2.TodoStatus.FromString,
        )
    self.GetTodos = channel.stream_stream(
        '/todos.Todos/GetTodos',
        request_serializer=todos__pb2.TodoRequest.SerializeToString,
        response_deserializer=todos__pb2.Todo.FromString,
        )
    self.GetTodo = channel.unary_unary(
        '/todos.Todos/GetTodo',
        request_serializer=todos__pb2.TodoRequest.SerializeToString,
        response_deserializer=todos__pb2.Todo.FromString,
        )
    self.TestTodo = channel.unary_unary(
        '/todos.Todos/TestTodo',
        request_serializer=todos__pb2.TestRequest.SerializeToString,
        response_deserializer=todos__pb2.TestResponse.FromString,
        )


class TodosServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTodos(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TestTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodosServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateTodo': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTodo,
          request_deserializer=todos__pb2.Todo.FromString,
          response_serializer=todos__pb2.TodoRequest.SerializeToString,
      ),
      'DeleteTodo': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTodo,
          request_deserializer=todos__pb2.TodoRequest.FromString,
          response_serializer=todos__pb2.TodoStatus.SerializeToString,
      ),
      'UpdateTodo': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateTodo,
          request_deserializer=todos__pb2.TodoRequest.FromString,
          response_serializer=todos__pb2.TodoStatus.SerializeToString,
      ),
      'GetTodos': grpc.stream_stream_rpc_method_handler(
          servicer.GetTodos,
          request_deserializer=todos__pb2.TodoRequest.FromString,
          response_serializer=todos__pb2.Todo.SerializeToString,
      ),
      'GetTodo': grpc.unary_unary_rpc_method_handler(
          servicer.GetTodo,
          request_deserializer=todos__pb2.TodoRequest.FromString,
          response_serializer=todos__pb2.Todo.SerializeToString,
      ),
      'TestTodo': grpc.unary_unary_rpc_method_handler(
          servicer.TestTodo,
          request_deserializer=todos__pb2.TestRequest.FromString,
          response_serializer=todos__pb2.TestResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'todos.Todos', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
