# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='todos.proto',
  package='todos',
  syntax='proto3',
  serialized_pb=_b('\n\x0btodos.proto\x12\x05todos\"\x1b\n\x0bTestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cTestResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\".\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t\"\x19\n\x0bTodoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"9\n\x0cTodoResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x19\n\x04todo\x18\x02 \x01(\x0b\x32\x0b.todos.Todo\"*\n\x08Response\x12\x1e\n\ttodo_resp\x18\x01 \x03(\x0b\x32\x0b.todos.Todo\"-\n\nTodoStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbe\x02\n\x05Todos\x12/\n\nCreateTodo\x12\x0b.todos.Todo\x1a\x12.todos.TodoRequest\"\x00\x12\x35\n\nDeleteTodo\x12\x12.todos.TodoRequest\x1a\x11.todos.TodoStatus\"\x00\x12\x35\n\nUpdateTodo\x12\x12.todos.TodoRequest\x1a\x11.todos.TodoStatus\"\x00\x12\x31\n\x08GetTodos\x12\x12.todos.TodoRequest\x1a\x0b.todos.Todo\"\x00(\x01\x30\x01\x12,\n\x07GetTodo\x12\x12.todos.TodoRequest\x1a\x0b.todos.Todo\"\x00\x12\x35\n\x08TestTodo\x12\x12.todos.TestRequest\x1a\x13.todos.TestResponse\"\x00\x62\x06proto3')
)




_TESTREQUEST = _descriptor.Descriptor(
  name='TestRequest',
  full_name='todos.TestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='todos.TestRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=49,
)


_TESTRESPONSE = _descriptor.Descriptor(
  name='TestResponse',
  full_name='todos.TestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='todos.TestResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=82,
)


_TODO = _descriptor.Descriptor(
  name='Todo',
  full_name='todos.Todo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todos.Todo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='todos.Todo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='todos.Todo.data', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=130,
)


_TODOREQUEST = _descriptor.Descriptor(
  name='TodoRequest',
  full_name='todos.TodoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todos.TodoRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=157,
)


_TODORESPONSE = _descriptor.Descriptor(
  name='TodoResponse',
  full_name='todos.TodoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='todos.TodoResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='todo', full_name='todos.TodoResponse.todo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=216,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='todos.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todo_resp', full_name='todos.Response.todo_resp', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=260,
)


_TODOSTATUS = _descriptor.Descriptor(
  name='TodoStatus',
  full_name='todos.TodoStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='todos.TodoStatus.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='todos.TodoStatus.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=307,
)

_TODORESPONSE.fields_by_name['todo'].message_type = _TODO
_RESPONSE.fields_by_name['todo_resp'].message_type = _TODO
DESCRIPTOR.message_types_by_name['TestRequest'] = _TESTREQUEST
DESCRIPTOR.message_types_by_name['TestResponse'] = _TESTRESPONSE
DESCRIPTOR.message_types_by_name['Todo'] = _TODO
DESCRIPTOR.message_types_by_name['TodoRequest'] = _TODOREQUEST
DESCRIPTOR.message_types_by_name['TodoResponse'] = _TODORESPONSE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['TodoStatus'] = _TODOSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestRequest = _reflection.GeneratedProtocolMessageType('TestRequest', (_message.Message,), dict(
  DESCRIPTOR = _TESTREQUEST,
  __module__ = 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.TestRequest)
  ))
_sym_db.RegisterMessage(TestRequest)

TestResponse = _reflection.GeneratedProtocolMessageType('TestResponse', (_message.Message,), dict(
  DESCRIPTOR = _TESTRESPONSE,
  __module__ = 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.TestResponse)
  ))
_sym_db.RegisterMessage(TestResponse)

Todo = _reflection.GeneratedProtocolMessageType('Todo', (_message.Message,), dict(
  DESCRIPTOR = _TODO,
  __module__ = 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.Todo)
  ))
_sym_db.RegisterMessage(Todo)

TodoRequest = _reflection.GeneratedProtocolMessageType('TodoRequest', (_message.Message,), dict(
  DESCRIPTOR = _TODOREQUEST,
  __module__ = 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.TodoRequest)
  ))
_sym_db.RegisterMessage(TodoRequest)

TodoResponse = _reflection.GeneratedProtocolMessageType('TodoResponse', (_message.Message,), dict(
  DESCRIPTOR = _TODORESPONSE,
  __module__ = 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.TodoResponse)
  ))
_sym_db.RegisterMessage(TodoResponse)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.Response)
  ))
_sym_db.RegisterMessage(Response)

TodoStatus = _reflection.GeneratedProtocolMessageType('TodoStatus', (_message.Message,), dict(
  DESCRIPTOR = _TODOSTATUS,
  __module__ = 'todos_pb2'
  # @@protoc_insertion_point(class_scope:todos.TodoStatus)
  ))
_sym_db.RegisterMessage(TodoStatus)



_TODOS = _descriptor.ServiceDescriptor(
  name='Todos',
  full_name='todos.Todos',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=310,
  serialized_end=628,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTodo',
    full_name='todos.Todos.CreateTodo',
    index=0,
    containing_service=None,
    input_type=_TODO,
    output_type=_TODOREQUEST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTodo',
    full_name='todos.Todos.DeleteTodo',
    index=1,
    containing_service=None,
    input_type=_TODOREQUEST,
    output_type=_TODOSTATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTodo',
    full_name='todos.Todos.UpdateTodo',
    index=2,
    containing_service=None,
    input_type=_TODOREQUEST,
    output_type=_TODOSTATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTodos',
    full_name='todos.Todos.GetTodos',
    index=3,
    containing_service=None,
    input_type=_TODOREQUEST,
    output_type=_TODO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTodo',
    full_name='todos.Todos.GetTodo',
    index=4,
    containing_service=None,
    input_type=_TODOREQUEST,
    output_type=_TODO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TestTodo',
    full_name='todos.Todos.TestTodo',
    index=5,
    containing_service=None,
    input_type=_TESTREQUEST,
    output_type=_TESTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODOS)

DESCRIPTOR.services_by_name['Todos'] = _TODOS

# @@protoc_insertion_point(module_scope)
